version: '3.8'

services:
  psi-omega-server:
    build: .
    image: psi-omega-server:latest
    ports:
      - "3000:3000"  # Expose the application port
    volumes:
      - .:/app  # Optional: Mount local files for development (can be removed for production)
    environment:
      - PORT=3000
    depends_on:
      - psql
    networks:
      - psi-omega-network

  psql:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - psi-omega-network

networks:
  psi-omega-network:
    driver: bridge

volumes:
  pgdata: