version: '3.8'
services:
  psi-omega-server:
    container_name: psi-omega-server
    image: nginx:latest
   # build: .
    volumes:
      - .:/app:/usr/share/nginx/html  # Optional: Mount local files for development (can be removed for production)
    ports:
      - 80:8000
      - 80:80  # Expose the application port
      - "3000:3000"  # Expose the application port
    environment:
      - PORT=3000
    depends_on:
      - psql
    networks:
      - psi-omega-network
    restard: always

  psql:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: psi-omega
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - psi-omega-network

networks:
  psi-omega-network:
    driver: bridge

volumes:
  pgdata: