version: '3.3'

services:
  psi-omega-server:
    container_name: psi-omega-server
    build: .
    image: psi-omega-server:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - psi-omega-network

  psql:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: psi-omega
      ADMIN_PASSWORD_HASH: "${ADMIN_PASSWORD_HASH:-}"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - psi-omega-network

networks:
  psi-omega-network:
    driver: bridge
