services:
  psi-omega-server:
    container_name: psi-omega-server
    build: .
    image: psi-omega-server:latest
    ports:
      - "3000:3000"  # Expose the application port
    volumes:
      - .:/app  # no idea if we need this or not
    environment:
      - PORT=3000
    depends_on:
      - psql
    networks:
      - psi-omega-network

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email it.dkepsiomega@gmail.com -d dekesrpi.org -d www.dekesrpi.org --agree-tos
