version: '3.8'

services:
  psi-omega-server:
    build: .
    image: psi-omega-server:latest
    ports:
      - "3000:3000"  # Expose the application port
    volumes:
      - .:/app  # no idea if we need this or not
    environment:
      - PORT=3000
    depends_on:
      - psql
    networks:
      - psi-omega-network

  psql:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ADMIN_PASSWORD_HASH: ${ADMIN_PASSWORD_HASH}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh  # Mount custom script
    entrypoint: ["./docker-entrypoint-initdb.d/init-db.sh"]
    networks:
      - psi-omega-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  
    depends_on:
      - psi-omega-server
    networks:
      - psi-omega-network

networks:
  psi-omega-network:
    driver: bridge

volumes:
  pgdata:
